<?php

/**
 * @file
 * This file contains all install related hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_xmlsitemap_uninstall() {
  $variables = array(
    'islandora_xmlsitemap_number_of_pids_to_process',
    'islandora_xmlsitemap_last_modified_value',
    'islandora_xmlsitemap_last_modified_field',
    'islandora_namespace_restriction_enforced',
  );
  array_walk($variables, 'variable_del');
}
