<?php
/**
 * @file
 * Main file for the islandora_xmlsitemap module.
 */


/**
 * Implements hook_cron().
 */
function islandora_xmlsitemap_cron() {
  module_load_include('inc', 'islandora_xmlsitemap', 'includes/islandora_xmlsitemap');
  // Currently there is no admin interface for this module
  // We want to port this to Drupal 7 and will do more there, like
  // adding a config for frequency and segmentation for sites with a lot
  // of Fedora content.  We may also want to check for and link to
  // certain datastreams.  This was developed for a simple Drupal 6 site.
  $lifetime = REQUEST_TIME - variable_get('islandora_xmlsitemap_generated_last', 0);
  // TODO: use islandora_xmlsitemap_minimum_lifetime in case we want to update
  // the database less frequently on larger sites.
  if ($lifetime < variable_get('xmlsitemap_minimum_lifetime', XMLSITEMAP_FREQUENCY_WEEKLY)) {
    return;
  }
  variable_set('islandora_xmlsitemap_generated_last', REQUEST_TIME);
  xmlsitemap_run_unprogressive_batch('islandora_xmlsitemap_update_customlinks');
}