<?php
/**
 * @file
 * Main file for the islandora_xmlsitemap module.
 */

define('ISLANDORA_XMLSITEMAP_PATH_PREFIX', 'islandora/object/');
/**
 * Implements hook_cron().
 */
function islandora_xmlsitemap_cron() {
  module_load_include('inc', 'islandora_xmlsitemap', 'includes/islandora_xmlsitemap');
  $lifetime = REQUEST_TIME - variable_get('islandora_xmlsitemap_generated_last', 0);
  if ($lifetime < variable_get('xmlsitemap_minimum_lifetime', XMLSITEMAP_FREQUENCY_WEEKLY)) {
    return;
  }
  variable_set('islandora_xmlsitemap_generated_last', REQUEST_TIME);
  xmlsitemap_run_unprogressive_batch('islandora_xmlsitemap_update_customlinks');
}

/**
 * Implements hook_islandora_object_purged.
 *
 * When an islandora object is purged we will attempt to remove it from the
 * xmlsitemap database.
 */
function islandora_xmlsitemap_islandora_object_purged($pid) {
  $loc = ISLANDORA_XMLSITEMAP_PATH_PREFIX . $pid;
  $id = db_query("SELECT id FROM {xmlsitemap} WHERE type = 'custom'
  AND loc = :loc", array(
    ':loc' => $loc
  ))->fetchCol();
  $id = reset($id);
  $value = xmlsitemap_link_delete('custom', array('id' => $id));
  if ($value > 0) {
    watchdog('islandora_xmlsitemap', 'Removed link %id with a path of %path from the xmlsitemap',
      array('%id' => $id, '%path' => $loc));
  }
}

/**
 * Implements hook_islandora_object_ingested.
 *
 * When an islandora object is ingested we will attempt to add a link to the
 * xmlsitemap database.
 */
function islandora_xmlsitemap_islandora_object_ingested($object) {
  $pid = $object->id;
  $loc = ISLANDORA_XMLSITEMAP_PATH_PREFIX . $pid;
  module_load_include('inc', 'islandora_xmlsitemap', 'includes/islandora_xmlsitemap');
  $value = islandora_xmlsitemap_add_link($pid, $object);
  if (!empty($value)) {
    watchdog('islandora_xmlsitemap', 'Added link %id with a path of %path to the xmlsitemap',
      array('%id' => $value['id'], '%path' => $loc));
  }
}

/**
 * Implements hook_form_alter.
 */
function islandora_xmlsitemap_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id != 'xmlsitemap_settings_form') {
    return;
  }
  $form['advanced']['islandora_xmlsitemap_start'] = array(
    '#type' => 'textfield',
    '#title' => 'Start indexing Islandora objects at this #',
    '#default_value' => variable_get('islandora_xmlsitemap_start'),
    '#size' => 10,
    '#element_validate' => array('element_validate_integer_positive'),
    '#description' => "This is the number the next cron run will start with.  Usually you don't need to modify this.",
  );
  $form['advanced']['islandora_xmlsitemap_number_of_pids_to_process'] = array(
    '#type' => 'textfield',
    '#title' => 'Maximum Number of Islandora links to process at once',
    '#size' => 10,
    '#element_validate' => array('element_validate_integer_positive'),
    '#default_value' => variable_get('islandora_xmlsitemap_number_of_pids_to_process', 1000),
    '#description' => 'This is the number of Islandora/Fedora links we will process at once',
  );
  $form['advanced']['islandora_xmlsitemap_sort_field'] = array(
    '#type' => 'textfield',
    '#title' => 'The Solr field to order results by',
    '#default_value' => variable_get('islandora_xmlsitemap_sort_field', 'fgs_createdDate_dt'),
    '#description' => 'Enter the name of a solr field to order results by.  A single valued date field  containing the date created would make sense here.',
  );
}

